# prometheus-kafka-adapter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kafka-adapter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-kafka-adapter
  template:
    metadata:
      labels:
        app: prometheus-kafka-adapter
    spec:
      containers:
        - name: adapter
          image: telefonica/prometheus-kafka-adapter:1.8.0
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER_LIST
              value: "your-kafka-broker-address:9092" # Point to your external Kafka or local Node IP
            - name: KAFKA_TOPIC
              value: "sre-pod-telemetry"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-adapter
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: prometheus-kafka-adapter
